#!/bin/bash
CWD=$(dirname "$(readlink -f "$0")")
BASE_PATH=$1

cd $BASE_PATH
set -euxo pipefail

for repo in gst-plugins-rs; do
  pushd $repo

  # strip binaries in debug mode
  mv Cargo.toml Cargo.toml.old
  sed s,'\[profile.release\]','[profile.release]\nstrip="debuginfo"', Cargo.toml.old > Cargo.toml 

  opts="-D prefix=/usr -D tests=disabled -D doc=disabled"

  if [[ $DEBUG == 'true' ]]; then
    if [[ $OPTIMIZATIONS == 'true' ]]; then
      opts="$opts -D buildtype=debugoptimized"
    else
      opts="$opts -D buildtype=debug"
    fi
  else
    opts="$opts -D buildtype=release -D b_lto=true"
  fi

  meson build $opts

  # This is needed for other plugins to be built properly
  ninja -C build install
  # This is where we'll grab build artifacts from
  DESTDIR=$BASE_PATH/compiled-binaries ninja -C build install
  popd
done

#gst-inspect-1.0

cd $CWD
